### ISSUE TITLE
Add new text brick results in an apparently disabled save button

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1095] opened 2015-02-12 22:49 UTC
STR:

- Start from scratch
- hit the + to add a brick
- pick the text brick

Two issues:
- I end up in a brick editing screen, which isn't where I expected to be (I thought i'd be in my app+a text brick)
- the save checkbox looks disabled, even though it responds to taps.

![2015-02-12 22 46 45](https://cloud.githubusercontent.com/assets/51278/6178683/3ab90188-b2c6-11e4-98cb-f28221640675.png)

**Comment by thisandagain** [comment] 2015-02-13 02:28
Duplicate of #1046

**Closed by thisandagain** 2015-02-13 02:28 UTC
