### ISSUE TITLE
App is eating my CPU

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#903] opened 2015-02-04 16:06 UTC
Running the app on desktop (os x 10.10.1) on FF Dev (37.0a2) is demanding a lot of resources. I'm not seeing the same thing on Chrome. Graph shows the tab opened 3 times and closed twice as viewed via the os activity monitor. 

![screenshot 2015-02-04 10 54 06](https://cloud.githubusercontent.com/assets/53411/6043871/8c74533e-ac5d-11e4-835e-ce46121067b4.png)

**Comment by k88hudson** [comment] 2015-02-04 19:39
Thanks for filing. This is a dupe of https://github.com/mozilla/webmaker-app/issues/782, but i will link this as well

**Closed by k88hudson** 2015-02-04 19:39 UTC
