### ISSUE TITLE
FFOS: adding a camera photo crashes app

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker-app#1295] opened 2015-02-24 00:28 UTC
*OS:* FFOS b2g 2.0.0.0-prerelease
*Browser:* N/A
*Screenshot:* N/A

**Repro Steps:**
1. In the inline editor for a photo block, tap the pencil
2. Choose "Camera"
3. Take photo, tap "select"

**Expected:** Edited photo in app is replaced with camera photo, return to app
**Actual:** Inline editor view returns to screen with original photo still in the block. after a few seconds, app crashes.

*note:* the new photo *is* being saved before the crash. Upon relaunching the app, the new photo has taken the place of the old one

**Comment by thisandagain** [comment] 2015-02-24 20:48
@gesa can you reproduce this using this build of FFOS (2.2) on the Flame? I cannot.
https://pvtbuilds.mozilla.org/pvt/mozilla.org/b2gotoro/nightly/mozilla-b2g37_v2_2-flame-kk-eng/2015/02/2015-02-15-16-25-03/

I'm able to reproduce on 2.0.0-prerelease but only by taking **lots** of photos sequentially. After some period of time, the amount of memory used by both the app and the camera application hits some device-specific threshold and the OS will kill the `webmaker` process in the background while the Camera app is open. This is similar to how inter-app communication works (or rather, doesn't) in Tarako.

**Comment by thisandagain** [comment] 2015-02-24 22:55
Walked through this with @gesa on Vidyo. Looks like this is resolved in Firefox OS 2.1/2.2

**Closed by thisandagain** 2015-02-24 22:55 UTC
Labels: bug
