### ISSUE TITLE
Weird alignment on webmaker-app for desktop screens

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-app#1264] opened 2015-02-20 21:03 UTC
It switches between center-aligned and left-aligned depending on what you click in the app.
This doesn't look too good:
![appmaker](https://cloud.githubusercontent.com/assets/134585/6309319/02cafbee-b944-11e4-8c90-13f1ab9bd4ec.png)

**Comment by thisandagain** [comment] 2015-02-20 21:20
Dupe of #1263

**Closed** 2015-02-20 21:20 UTC
