### ISSUE TITLE
change apk file name

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-app#1258] opened 2015-02-20 18:39 UTC
http://mzl.la/installwm downloads "CordovaApp-debug.apk" which is pretty horrible.

how about "Webmaker.apk"

**Comment by gesa** [comment] 2015-02-23 23:36
Okay so according to my research, I think we need to add `!platforms/android/AndroidManifest.xml` and `!platforms/firefoxos/config.xml` to `.gitignore`. From there, *allegedly* this command should change the name of our android apk: `android update project --name webmaker --path platforms/android --subprojects`. Only, based on my testing, it doesn't.

According to Cordova, this is a known issue, the resolution to which had a PR opened [yesterday](https://github.com/apache/cordova-lib/pull/171).

**Comment by ncalexan** [comment] 2015-05-03 20:19
The <a href="https://github.com/apache/cordova-lib/pull/171">linked PR</a> shows how to change the *Activity* name, not the APK name.  (The Activity name will show appear in the home screen, since the single Cordova Activity is also a launch activity that will appear in the list of applications.)

I'm more concerned that we may be shipping a debug Android build to end users.  Such a build can be openly inspected and modified by anybody with a USB cable to the device.  In general, we should never ship a debug build in the wild.

**Comment by ncalexan** [comment] 2015-05-03 20:25
Ah!  But it appears Cordova may be setting the APK name to the Activity name, which makes a lot of sense, since there's only one Activity.

**Comment by ncalexan** [comment] 2015-05-03 20:31
I'm new to this and curious to understand what process (Travis job?) is producing the APK that http://mzl.la/installwm links to, namely https://webmaker-dist.s3.amazonaws.com/staging/android/CordovaApp-debug.apk.  I expect it's https://github.com/mozilla/webmaker-app-cordova but I don't see any output like that locally, since w-a-cordova uses Gradle and the .travis.yml file references ant.

**Comment by thisandagain** [comment] 2015-05-04 15:03
Hey @ncalexan ,
Travis produces the APK using `ant` within the `webmaker-app-cordova` repo. Details are available here:
https://github.com/mozilla/webmaker-app-cordova/blob/master/.travis.yml

I am going to close this as the issue is resolved in the `v1` branch which we should be merging into `master` near the end of the week:
https://github.com/mozilla/webmaker-app/tree/v1

**Closed** 2015-05-04 15:03 UTC
Labels: enhancement
