### ISSUE TITLE
pre-load first screen of newest category in discover tab

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1099] opened 2015-02-12 23:01 UTC
STR:
 - hit discover tab
 - oh, look there aren't many featured apps
 - let's check out newest
 - there's nothing there!
 - hit make tab

(meanwhile, the XHR to fill in the newest tab returns but the impatient user has walked away)

Probably two-step mitigation:
 - have some placeholder text under the Newest tab that explains that we're searching for latest & greatest, w/ a spinner or whatnot
 - aggressively just fetch 10 relatively recent apps, even if they're not _really_ the latest 10.  Low latency response is way more important than actually being the latest.  As in, have a no-database-hitting endpoint which is low-latency, and is updated even just hourly.

**Comment by thisandagain** [comment] 2015-02-13 02:27
Duplicate of #1032

**Closed by thisandagain** 2015-02-13 02:27 UTC
