### ISSUE TITLE
counter button layout gets confused on touch

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1132] opened 2015-02-13 01:26 UTC
![2015-02-13 01 20 36](https://cloud.githubusercontent.com/assets/51278/6180613/565ff0f2-b2dc-11e4-8302-6f1ce5cea1bc.png)

**Comment by davidascher** [comment] 2015-02-13 01:29
- [ ] The orange ring shouldn't exist as far as I can tell
- [ ] the height of the number box should never change.

**Comment by alicoding** [comment] 2015-02-20 14:10
Is that Lollipop?

**Comment by alicoding** [comment] 2015-02-20 14:11
I've tried on 4.4 and 5.0 and still can't reproduce this. @davidascher Can you confirm if this is fixed on your end?

**Closed** 2015-05-04 15:08 UTC
Labels: bug
